[tool.poetry]
name = "teachableautogen"
version = "0.1.0"
description = ""
authors = ["George Simbe <GeorgeSimbe13@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.12"




[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
